### ISSUE TITLE
AuthFlow().start() no callback and login view does not dismiss

### ISSUE THREAD

**Issue by leonylcatwork** [Authing/guard-ios#1]
Otherwise please fill in as much of the template below as possible or you can give us a pr.
-->

- **Version**:
Guard 1.3.4
Xcode 14.1 (14B47b)

#### Severity:
High - The main functionality of the application does not work, API breakage, repo format breakage, etc.
Cannot get callback for Authing.start() 

#### Description:
1. create new swift project
2. SPM add package https://github.com/Authing/guard-ios（currently Guard V1.3.4)
3. In ViewController.swift viewDidLoad() call Authing.start($appid)
4. Then call AuthFlow().start() and completion sign in and mfa, but do not receive callback, nor does the login view dismiss. 

example: https://github.com/leonylcatwork/AuthingV2

**Comment by jiananMars** [comment]
我们使用了你的 demo 没有复现没有回调的错误。
无法 dismiss 是因为代码块放在了 viewDidApperar 中。

<img width="500" alt="WeChat01d00d6428b177f1ed354441c872f326" src="https://user-images.githubusercontent.com/10389329/212296067-a40d4b62-d1eb-425c-a7a9-0e5347d769f8.png">
